//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    public partial class bacsi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bacsi()
        {
            this.datlichkhams = new HashSet<datlichkham>();
        }
    
        public int id_bacsi { get; set; }
        public string hovaten { get; set; }
        public string chucvu { get; set; }
        public string bophan { get; set; }
        public Nullable<int> sdt { get; set; }
        public Nullable<int> namsinh { get; set; }
        public Nullable<int> cmnd { get; set; }
        public string hinhanh { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        public string quatrinhcongtac { get; set; }
        public string kinhnghiem { get; set; }
        public Nullable<int> id_khoa { get; set; }
        public string diachi { get; set; }
        public Nullable<int> id_benhnhan { get; set; }
    
        public virtual khoa khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datlichkham> datlichkhams { get; set; }
    }
}
