//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class bacsi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bacsi()
        {
            this.datlichkhams = new HashSet<datlichkham>();
            this.LOGINs = new HashSet<LOGIN>();
        }
        [Display(Name = "Mã bác sĩ")]

        public int id_bacsi { get; set; }
        [Display(Name = "Họ Và Tên")]

        [Required(ErrorMessage = "vui lòng nhập họ và tên")]
        public string hovaten { get; set; }

        [Display(Name = "Chức Vụ")]

        public string chucvu { get; set; }

        [Display(Name = "Bộ Phận")]
        public string bophan { get; set; }

        [Display(Name = "Số Điện Thoại")]
        [Required(ErrorMessage = "vui lòng nhập Số Điện Thoại")]
        [Phone(ErrorMessage = "Vui lòng nhập đúng số điện thoại")]
        [StringLength(maximumLength: 10, MinimumLength = 10, ErrorMessage = "Số điện thoại không hợp lệ")]
        public Nullable<int> sdt { get; set; }

        [Display(Name = "Năm sinh")]
        public Nullable<int> namsinh { get; set; }

        [Display(Name = "CMND")]
        [Required(ErrorMessage = "vui lòng nhập CMND")]
        [StringLength(maximumLength: 9, MinimumLength = 9, ErrorMessage = "CMND Phải 9 số")]
        public Nullable<int> cmnd { get; set; }

        [Display(Name = "Hình ảnh")]
        [Required(ErrorMessage = "vui lòng upload hình")]
        public string hinhanh { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "Qúa trình công tác")]
        public string quatrinhcongtac { get; set; }

        [Display(Name = "Kinh Nghiệm")]
        public string kinhnghiem { get; set; }

        [Display(Name = "Khoa")]
        public Nullable<int> id_khoa { get; set; }

        [Display(Name = "Địa chỉ")]
        public string diachi { get; set; }

        public Nullable<int> id_benhnhan { get; set; }

        [Display(Name = "Ngày làm việc")]
        public string ngaylamviec { get; set; }
    
        public virtual khoa khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datlichkham> datlichkhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIN> LOGINs { get; set; }
    }
}
