//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiet_HoaDon
    {
        public int id_hoadon { get; set; }
        public int id_goikham { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> dongia { get; set; }
    
        public virtual goi_kham_suc_khoe goi_kham_suc_khoe { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
