//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class dangkykhambenh
    {
        public int id_benhnhan { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "vui lòng nhập họ tên")]
        public string hovaten { get; set; }
        public Nullable<double> namsinh { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public Nullable<System.DateTime> ngaykham { get; set; }
        public string giokham { get; set; }
        public string motatrieuchung { get; set; }
        public string khac { get; set; }
        public string sodienthoai { get; set; }
    }
}
