//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_DKKHAMBENH_ONLINEEntities : DbContext
    {
        public QL_DKKHAMBENH_ONLINEEntities()
            : base("name=QL_DKKHAMBENH_ONLINEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bacsi> bacsis { get; set; }
        public virtual DbSet<datlichkham> datlichkhams { get; set; }
        public virtual DbSet<Hosobenhnhan> Hosobenhnhans { get; set; }
        public virtual DbSet<khoa> khoas { get; set; }
        public virtual DbSet<khoangoai> khoangoais { get; set; }
        public virtual DbSet<khoanoi> khoanois { get; set; }
        public virtual DbSet<LOGIN> LOGINs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tintuc> tintucs { get; set; }
        public virtual DbSet<goi_kham_suc_khoe> goi_kham_suc_khoe { get; set; }
        public virtual DbSet<Chitiet_HoaDon> Chitiet_HoaDon { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<dangkykhambenh> dangkykhambenhs { get; set; }
    }
}
