//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class datlichkham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datlichkham()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
        [Display(Name = "Mã bệnh nhân")]

        public int id_benhnhan { get; set; }
        [Display(Name ="Họ Và Tên")]
        [Required(ErrorMessage = "vui lòng nhập họ tên")]
        public string hoten { get; set; }

        [Display(Name = "Ngày Sinh")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ngaysinh { get; set; }

        [Display(Name = "Giới tính")]
        public string gioitinh { get; set; }

        [Display(Name = "Số Điện Thoại")]
        [Required(ErrorMessage = "vui lòng nhập số điện thoại")]
        [Phone(ErrorMessage = "Vui lòng nhập đúng số điện thoại")]
        [StringLength(maximumLength: 10, MinimumLength = 10, ErrorMessage = "Số điện thoại phải 10 số")]
        public string sodienthoai { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "vui lòng nhập Email")]
        [EmailAddress(ErrorMessage = "Vui lòng nhập đúng địa chỉ Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "vui lòng nhập Địa chỉ")]
        public string diachi { get; set; }

        [Display(Name = "Mô Tả Triệu Chứng")]
        public string motatrieuchung { get; set; }

        [Display(Name = "Ngày Khám")]
        public Nullable<System.DateTime> ngaykham { get; set; }

        [Display(Name = "Giờ khám")]
        public string giokham { get; set; }

        [Display(Name = "Hình Đại Diện")]
        public string hinhdaidien { get; set; }

        [Display(Name = "Mật Khẩu")]
        [Required(ErrorMessage = "vui lòng nhập mật khẩu")]
        [DataType(DataType.Password)]
        public string matkhau { get; set; }

        [Display(Name = "Mã Bác sĩ")]
        public Nullable<int> id_bacsi { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }

        [Display(Name = "Kích hoạt tài khoản")]
        public bool IsEmailVerified { get; set; }
    
        public virtual bacsi bacsi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
