//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class datlichkham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datlichkham()
        {
            this.HOADONs = new HashSet<HOADON>();
        }

        public int id_benhnhan { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "vui lòng nhập họ tên")]
        public string hoten { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "vui lòng nhập ngày sinh")]
        public Nullable<System.DateTime> ngaysinh { get; set; }
        //[Required(ErrorMessage = "vui lòng chọn giới tính")]
        public string gioitinh { get; set; }

        [Required(ErrorMessage = "vui lòng nhập số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        public string sodienthoai { get; set; }
        [Required(ErrorMessage = "vui lòng nhập Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        //[Required(ErrorMessage = "vui lòng nhập địa chỉ")]
        public string diachi { get; set; }

        //[Required(ErrorMessage = "vui lòng nhập mô tả triệu chứng")]
        [DataType(DataType.Text)]
        public string motatrieuchung { get; set; }
        //[DataType(DataType.Time)]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "vui lòng ngày khám")]

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]


        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> ngaykham { get; set; }
        public string hinhdaidien { get; set; }

        [Required(ErrorMessage = "vui lòng nhập mật khẩu")]
        [DataType(DataType.Password)]
        public string matkhau { get; set; }
        public Nullable<int> id_bacsi { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public bool IsEmailVerified { get; set; }

        public virtual bacsi bacsi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:HH:mm}")]
        [Required(ErrorMessage = "vui lòng nhập giờ khám")]

        public string giokham { get; set; }

    }
}
