//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datlichkham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datlichkham()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int id_benhnhan { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string sodienthoai { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public string motatrieuchung { get; set; }
        public Nullable<System.DateTime> ngaykham { get; set; }
        public string hinhdaidien { get; set; }
        public string matkhau { get; set; }
        public Nullable<int> id_bacsi { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public bool IsEmailVerified { get; set; }
        public string giokham { get; set; }
    
        public virtual bacsi bacsi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
