//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class goi_kham_suc_khoe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public goi_kham_suc_khoe()
        {
            this.Chitiet_HoaDon = new HashSet<Chitiet_HoaDon>();
        }
    
        public int id_goikham { get; set; }
        public string ten_goikham { get; set; }
        public Nullable<double> gia { get; set; }
        public string gioithieu { get; set; }
        public Nullable<int> soluong { get; set; }
        public string mota { get; set; }
        public string chitiet { get; set; }
        public string hinhanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiet_HoaDon> Chitiet_HoaDon { get; set; }
    }
}
