//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class goi_kham_suc_khoe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public goi_kham_suc_khoe()
        {
            this.Chitiet_HoaDon = new HashSet<Chitiet_HoaDon>();
        }

        [Display(Name = "Mã gói khám")]
        public int id_goikham { get; set; }

        [Display(Name = "Tên gói khám")]
        [Required(ErrorMessage = "vui lòng nhập tên gói khám")]
        public string ten_goikham { get; set; }

        [Display(Name = "Gía")]
        [Required(ErrorMessage = "vui lòng nhập giá gói khám")]
        public Nullable<double> gia { get; set; }

        [Display(Name = "Giới thiệu")]
        [Required(ErrorMessage = "vui lòng nhập giới thiệu")]
        public string gioithieu { get; set; }

        [Display(Name = "Số Lượng")]
        [Required(ErrorMessage = "vui lòng nhập số lượng")]
        public Nullable<int> soluong { get; set; }

        [Display(Name = "Mô Tả")]
        [Required(ErrorMessage = "vui lòng nhập mô tả")]
        public string mota { get; set; }

        [Display(Name = "Chi tiết")]
        [Required(ErrorMessage = "vui lòng nhập chi tiết")]
        public string chitiet { get; set; }

        [Display(Name = "Hình ảnh")]
        [Required(ErrorMessage = "vui lòng Upload ảnh")]
        public string hinhanh { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiet_HoaDon> Chitiet_HoaDon { get; set; }
    }
}
