//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.Chitiet_HoaDon = new HashSet<Chitiet_HoaDon>();
        }
    
        public int id_hoadon { get; set; }
        public string dathanhtoan { get; set; }
        public string tinhtrang_goikham { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public Nullable<int> id_benhnhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiet_HoaDon> Chitiet_HoaDon { get; set; }
        public virtual datlichkham datlichkham { get; set; }
    }
}
