//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosobenhnhan
    {
        public int id_hoso { get; set; }
        public string cmnd { get; set; }
        public string dantoc { get; set; }
        public string nghenghiep { get; set; }
        public string chohientai { get; set; }
        public Nullable<int> cannang { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> chieucao { get; set; }
        public string tieusu { get; set; }
        public Nullable<int> id_khoa { get; set; }
        public string chandoan { get; set; }
        public string ketqua { get; set; }
        public Nullable<int> id_benhnhan { get; set; }
    }
}
