//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khoangoai
    {
        public int id_khoangoai { get; set; }
        public string hohap { get; set; }
        public string tieuhoa { get; set; }
        public string timmach { get; set; }
        public string truyennhiem { get; set; }
    }
}
