//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khoanoi
    {
        public int id_khoanoi { get; set; }
        public string gan { get; set; }
        public string mat { get; set; }
        public string tụy { get; set; }
        public string duongtieuhoa { get; set; }
        public string chanthuong { get; set; }
    }
}
