//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LOGIN
    {
        [Display(Name = "ID")]
        public int ma_user { get; set; }
        [Display(Name = "Tên tài khoản")]
        public string name_user { get; set; }
        [Display(Name = "Mật Khẩu")]
        public string password { get; set; }
        [Display(Name = "Quyền")]
        public Nullable<int> quyen { get; set; }
        [Display(Name = "Mã bác sĩ")]
 
        public Nullable<int> id_bacsi { get; set; }
    
        public virtual bacsi bacsi { get; set; }
    }
}
