//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Thietlap_Trangchu
    {
        [Display(Name = "ID")]
        public int id { get; set; }
        [Display(Name = "Tiêu đề 1")]
        public string tieude1 { get; set; }
        [Display(Name = "Mô tả 1")]
        public string mota1 { get; set; }
        [Display(Name = "nội dung 1")]
        public string noidung1 { get; set; }
        [Display(Name = "hình ảnh 1")]
        public string hinhanh1 { get; set; }
        public HttpPostedFileBase ImageFile1 { get; set; }
        [Display(Name = "tiêu đề 2")]
        public string tieude2 { get; set; }
        [Display(Name = "mô tả 2")]
        public string mota2 { get; set; }
        [Display(Name = "nội dung 2")]
        public string noidung2 { get; set; }
        [Display(Name = "hình ảnh 2")]
        public string hinhanh2 { get; set; }
        public HttpPostedFileBase ImageFile2 { get; set; }
    }
}
