//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tintuc
    {
        [Display(Name = "Mã bài viết")]
        public int id_tintuc { get; set; }
        [Display(Name = "Tên Bài viết")]
        [Required(ErrorMessage = "vui lòng nhập tên bài viết")]
        public string tenbaiviet { get; set; }

        [Display(Name = "Ngày Đăng")]
        [Required(ErrorMessage = "vui lòng nhập Ngày đăng")]
        public Nullable<System.DateTime> ngaydang { get; set; }

        [Display(Name = "Hình Ảnh")]
        [Required(ErrorMessage = "vui lòng upload hình ảnh")]
        public string hinhanh { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "Nội dung")]
        [Required(ErrorMessage = "vui lòng nhập Nội dung bài viết")]
        public string noidung { get; set; }
        [Display(Name = "Tiêu đề")]
        [Required(ErrorMessage = "vui lòng nhập tiêu đề bài viết")]
        public string SEOTitle { get; set; }

        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "vui lòng nhập Mô tả bài viết")]
        public string SEOdescriptison { get; set; }
    }
}
