//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan_qldkonline.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class tintuc
    {
        public int id_tintuc { get; set; }
        public string tenbaiviet { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public string hinhanh { get; set; }
        public HttpPostedFileBase ImageFile { get; set;}
        public string noidung { get; set; }
        public string SEOTitle { get; set; }
        public string SEOdescriptison { get; set; }
    }
}
